### ISSUE TITLE
移动端微信内点击进度条无法正确匹配歌词

### ISSUE THREAD

**Issue by cvmax** [moefront/muse#15]
iOS 最新系统，微信也是最新，一个小项目中用到了 up 主的 ymplayer，但是发现多次点击滚动条后，就出现无法正确匹配歌词的状况了。

**Comment by cvmax** [comment]
经测试，桌面端 Firefox 是没有这种情况的。望 up 明察。

**Comment by kirainmoe** [comment]
可能是原版本对歌词解析同步实现方法的问题。请尝试一下更新最新版本，这里merge了frank-deng的pull request #14，其中提到了对歌词解析和同步的更新。
因为最近学业实在太忙，没时间打理这些项目的事情，我自己没有尝试，不妨尝试一下看看问题是否解决。如果问题依旧，过段时间我再尝试解决此问题。

**Comment by cvmax** [comment]
新版的 js 文件更新之后，似乎有更多的问题，没仔细看。匆匆切回了第一版... 待我仔细看看第一版的代码，还是在这个基础上改。 @kirainmoe

**Comment by kirainmoe** [comment]
我在 Windows Blue + Firefox 45.0.2 && Chrome 49 没有发现拖动点击进度条不准的问题哎……
但是据说 Firefox 中 <audio> 对 .mp3 格式的声音文件支持不好，不知道是不是这个原因……
不知是否方便提供一个 demo 之类，这样定位问题可能会方便一些w

**Comment by cvmax** [comment]
诶，对，我的都是.mp3文件。demo 稍等。
